AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  GetTeachersList

  Sample SAM Template for GetTeachersList
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GetTeachersListFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: function/
      Handler: app.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetTeachersListApi:
    Description: "API Gateway endpoint URL for Prod stage for GetTeachersList function"
    Value: !Sub "https://cls9taco80.execute-api.us-west-2.amazonaws.com/dev"
  GetTeachersListFunction:
    Description: "GetTeachersList Lambda Function ARN"
    Value: !GetAtt GetTeachersListFunction.Arn
  GetTeachersListFunctionIamRole:
    Description: "Implicit IAM Role created for GetTeachersList function"
    Value: !GetAtt GetTeachersListFunctionRole.Arn
