AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ExecuteStoredProcedure

  Sample SAM Template for ExecuteStoredProcedure
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ExecuteStoredProcedureFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: function/
      Handler: app.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      # Events:
      #   ExecuteStoredProcedure:
      #     Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #     Properties:
      #       Path: /hello
      #       Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ExecuteStoredProcedureApi:
    Description: "API Gateway endpoint URL for Prod stage for ExecuteStoredProcedure function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ExecuteStoredProcedureFunction:
    Description: "ExecuteStoredProcedure Lambda Function ARN"
    Value: !GetAtt ExecuteStoredProcedureFunction.Arn
  ExecuteStoredProcedureFunctionIamRole:
    Description: "Implicit IAM Role created for ExecuteStoredProcedure function"
    Value: !GetAtt ExecuteStoredProcedureFunctionRole.Arn
